package com.spukmk2me.spukmk2mesceneeditor.gui;

import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

import com.spukmk2me.video.IVideoDriver;
import com.spukmk2me.optional.scene.ResourceManager;

public class ImageDialog extends javax.swing.JDialog
{
    public ImageDialog( ResourceManager manager, IVideoDriver vdriver,
        Frame parent, boolean modal )
    {
        super( parent, modal );
        initComponents();
        m_manager = manager;
        m_vdriver = vdriver;
        Initialise();
    }

    private void Initialise()
    {
        Reload();
    }

    private void Reload()
    {
        DefaultListModel model = (DefaultListModel)m_imageList.getModel();
        int n = m_manager.GetNumberOfResources( ResourceManager.RT_IMAGE );

        model.clear();

        for ( int i = 0; i != n; ++i )
        {
            model.addElement(
                m_manager.
                GetResource( i, ResourceManager.RT_IMAGE ).
                GetCreationData().c_proxyName );
        }

        m_imageList.setModel( model );
        m_imageList.setSelectionMode( ListSelectionModel.SINGLE_SELECTION );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_imageList = new javax.swing.JList();
        m_addButton = new javax.swing.JButton();
        m_removeButton = new javax.swing.JButton();
        m_closeButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Images:");

        m_imageList.setModel( new DefaultListModel() );
        jScrollPane1.setViewportView(m_imageList);

        m_addButton.setText("Add");
        m_addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_addButtonActionPerformed(evt);
            }
        });

        m_removeButton.setText("Remove");
        m_removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_removeButtonActionPerformed(evt);
            }
        });

        m_closeButton.setText("Close");
        m_closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_closeButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m_removeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(m_closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(m_addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_removeButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(m_closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_addButtonActionPerformed

        ImageDialog_AddImage dlg = new ImageDialog_AddImage( m_manager,
           m_vdriver, this, true );

        dlg.setVisible( true );
        Reload();
    }//GEN-LAST:event_m_addButtonActionPerformed

    private void m_closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_closeButtonActionPerformed

        this.dispose();
    }//GEN-LAST:event_m_closeButtonActionPerformed

    private void m_removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_removeButtonActionPerformed

        int index = m_imageList.getSelectedIndex();
        
        if ( index != -1 )
        {
            m_manager.RemoveResource( index, ResourceManager.RT_IMAGE );
            ((DefaultListModel)m_imageList.getModel()).remove( index );
        }
    }//GEN-LAST:event_m_removeButtonActionPerformed

    private IVideoDriver    m_vdriver;
    private ResourceManager m_manager;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton m_addButton;
    private javax.swing.JButton m_closeButton;
    private javax.swing.JList m_imageList;
    private javax.swing.JButton m_removeButton;
    // End of variables declaration//GEN-END:variables
}
